adding submission for topic 4
ika-rwth-aachen/acdc-research-projects pull request #5
Opened 2023-10-21 20:06 UTC by Suchit153

2023-10-23 08:41 UTC, lreiher commented
Thanks for opening this PR!

It looks like you have added your content as a submodule. I cannot access that submodule. I would also suggest to consider placing the files directly inside this repository without yet another submodule.

2023-10-23 22:15 UTC, Suchit153 commented
> Thanks for opening this PR!
> 
> It looks like you have added your content as a submodule. I cannot access that submodule. I would also suggest to consider placing the files directly inside this repository without yet another submodule.

Done

2023-10-24 05:48 UTC, lreiher requested changes

2023-10-24 05:48 UTC, lreiher commented on reports/04-Time-Series-Inverse-Perspective-Mapping/2023_batu_suchit/python_scripts/Untitled.ipynb
It looks like you still have some temporary leftover scripts that can be deleted, e.g., this `Untitled.ipynb`. I suggest to take a look at all files once more and delete those that are not required.

2023-10-24 05:48 UTC, lreiher commented on reports/04-Time-Series-Inverse-Perspective-Mapping/2023_batu_suchit/example_outputs/segmented_image_files/right/example_scene_0.npz
You have a lot of `.npz` files. Can you please track them in [Git LFS](https://git-lfs.com/)? As seen in the [`.gitattributes`](https://github.com/ika-rwth-aachen/acdc-research-projects/blob/main/.gitattributes), I have already pre-configured a lot of file extensions for Git LFS, but I have missed `.npz`.

You can start tracking those by running `git lfs track "*.npz"`. Afterwards, however, you should also try to check whether those files already committed need to be adjusted, cause they do not get tracked by Git LFS automatically, if they have been checked in before.

The easiest solution could be to re-fork the repository or switch to a different branch, first track the files in Git LFS, and only afterwards commit them.

2023-10-24 05:48 UTC, lreiher commented on reports/04-Time-Series-Inverse-Perspective-Mapping/2023_batu_suchit/report.ipynb
Please list your contribution in [this section of the README](https://github.com/ika-rwth-aachen/acdc-research-projects#finished-research-projects).

2023-10-29 19:45 UTC, Suchit153 commented on reports/04-Time-Series-Inverse-Perspective-Mapping/2023_batu_suchit/python_scripts/Untitled.ipynb
Sorry about that... I thought I had deleted that file, but had only done it in my local
I have gone through the rest as well, everything else seems to be in order

2023-10-29 20:42 UTC, closed without merging